server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Yeuin37853#*#
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xiaoyang.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
